package support

var allPatterns = []map[string]string{
	JSFrameworksPatterns,
	CSSUIPatterns,
	WebTechnologyPatterns,
	MarketingAnalyticsPatterns,
	PluginsPatterns,
	WAFPatterns,
	CMSPatterns,
}


var JSFrameworksPatterns = map[string]string{
	"jQuery":          `src=["'][^"']*jquery[^"']*["']`,
	"React":           `React(?:DOM)?\.`,
	"Vue.js":          `vue(?:\.js)?["']?`,
	"Angular":         `angular(?:\.module|\.)?`,
	"Ember.js":        `Ember(?:\.|["'])`,
	"Backbone.js":     `Backbone(?:\.|["'])`,
	"Preact":          `Preact(?:\.|["'])`,
}


var CSSUIPatterns = map[string]string{
	"Bootstrap":       `(href|src)=["'][^"']*bootstrap[^"']*["']`,
	"Tailwind CSS":    `href=["'][^"']*tailwind(?:\.min)?\.css["']`,
	"Materialize":     `materialize(?:\.min)?\.css`,
	"Bulma":           `href=["'][^"']*bulma(?:\.min)?\.css["']`,
	"FontAwesome":     `href=["'][^"']*font[-]?awesome[^"']*["']`,
}


var WebTechnologyPatterns = map[string]string{
	"Next.js":         `__NEXT_DATA__`,
	"Nuxt.js":         `__NUXT__`,
}


var MarketingAnalyticsPatterns = map[string]string{
	"Google Tag Manager": `(?i)(https://www.googletagmanager.com/gtm\.js\?id=GTM-[A-Z0-9]+|GTM-[A-Z0-9]+|dataLayer\s*=)`,
	"Google Analytics":   `www\.google-analytics\.com/analytics\.js`,
	"Hotjar":             `static\.hotjar\.com`,
	"Segment":            `cdn\.segment\.com`,
}


var PluginsPatterns = map[string]string{
	"LazyLoad": `(?i)(loading=["']lazy["']|data-src=|data-lazy=|lazyload(?:\.min)?\.js|class=["'][^"']*lazy[^"']*["'])`,
	"a3LazyLoad": `(?i)(a3-lazy-load|data-lazy-src|data-lazy-srcset|class=["'][^"']*a3-lazy-load[^"']*["'])`,
	"LazyLoadPlugin": `(?i)(rocket-lazy-load|data-lazy-src|data-lazy-srcset|class=["'][^"']*lazyload[^"']*["'])`,
	"BJLazyLoad": `(?i)(bj-lazy-load|data-lazy-src|data-lazy-srcset|class=["'][^"']*lazyload[^"']*["'])`,
	"EasyOptimizer": `(?i)(easy-optimizer|data-lazy-src|data-lazy-srcset|class=["'][^"']*lazyload[^"']*["'])`,
	"YoastSEO": `(?i)(yoast-seo|wpseo|class=["'][^"']*yoast[^"']*["'])`,
	"FileBird": `(?i)(filebird-lazyload|data-src|data-lazy-src|class=["'][^"']*filebird[^"']*["'])`,
	"Elementor": `(?i)(elementor-|data-elementor-type|class=["'][^"']*elementor[^"']*["'])`,
	"WooCommerce": `(?i)(woocommerce-|data-product-id|class=["'][^"']*woocommerce[^"']*["'])`,
	"WPForms": `(?i)(wpforms-|data-wpforms-form|class=["'][^"']*wpforms[^"']*["'])`,
	"GravityForms": `(?i)(gform_|\bgform\b|data-gform|class=["'][^"']*gform[^"']*["'])`,
	"WPBakery": `(?i)(vc_|wpb_|data-vc-|class=["'][^"']*wpb[^"']*["'])`,
	"SliderRevolution": `(?i)(rev_slider|tp-caption|class=["'][^"']*revslider[^"']*["'])`,
	"ContactForm7": `(?i)(wpcf7-form|wpcf7-submit|class=["'][^"']*wpcf7[^"']*["'])`,
	"Jetpack": `(?i)(jetpack-|data-jetpack-|class=["'][^"']*jetpack[^"']*["'])`,
	"Akismet": `(?i)(akismet-|data-akismet-|class=["'][^"']*akismet[^"']*["'])`,
	"Wordfence": `(?i)(wordfence-|wf-|data-wordfence-|class=["'][^"']*wordfence[^"']*["'])`,
	"WPSuperCache": `(?i)(wpsc_|wp-super-cache|data-wpsc-|class=["'][^"']*wpsc[^"']*["'])`,
	"AllinOneSEO": `(?i)(aioseo-|data-aioseo-|class=["'][^"']*aioseo[^"']*["'])`,
	"MonsterInsights": `(?i)(monsterinsights-|data-monsterinsights-|class=["'][^"']*monsterinsights[^"']*["'])`,
	"ShortcodesUltimate": `(?i)(su-|data-su-|class=["'][^"']*su[^"']*["'])`,
	"WPMailSMTP": `(?i)(wp-mail-smtp|data-wp-mail-smtp|class=["'][^"']*wp-mail-smtp[^"']*["'])`,
	"EasyDigitalDownloads": `(?i)(edd-|data-edd-|class=["'][^"']*edd[^"']*["'])`,
	"Redirection": `(?i)(redirection-|data-redirection-|class=["'][^"']*redirection[^"']*["'])`,
	"BrokenLinkChecker": `(?i)(blc_|data-blc-|class=["'][^"']*blc[^"']*["'])`,
	"WP Rocket": `(?i)(wp-rocket|data-wp-rocket-|class=["'][^"']*wp-rocket[^"']*["'])`,
	"Smush Image Compression": `(?i)(smush-|data-smush-|class=["'][^"']*smush[^"']*["'])`,
	"Imagify": `(?i)(imagify-|data-imagify-|class=["'][^"']*imagify[^"']*["'])`,
	"Cloudflare Cache": `(?i)(cloudflare-|data-cloudflare-|class=["'][^"']*cloudflare[^"']*["'])`,
	"NitroPack Cache": `(?i)(nitropack-|data-nitropack-|class=["'][^"']*nitropack[^"']*["'])`,
	"LiteSpeed Cache": `(?i)(litespeed-|data-litespeed-|class=["'][^"']*litespeed[^"']*["'])`,
	"WP Fastest Cache": `(?i)(wp-fastest-cache|data-wp-fastest-cache-|class=["'][^"']*wp-fastest-cache[^"']*["'])`,
	"WP Optimize": `(?i)(wp-optimize|data-wp-optimize-|class=["'][^"']*wp-optimize[^"']*["'])`,
	"Hummingbird": `(?i)(hummingbird-|data-hummingbird-|class=["'][^"']*hummingbird[^"']*["'])`,
	"WPML": `(?i)(wpml-|data-wpml-|class=["'][^"']*wpml[^"']*["'])`,
	"Polylang": `(?i)(polylang-|data-polylang-|class=["'][^"']*polylang[^"']*["'])`,
	"WP Reset": `(?i)(wp-reset-|data-wp-reset-|class=["'][^"']*wp-reset[^"']*["'])`,
	"Duplicator": `(?i)(duplicator-|data-duplicator-|class=["'][^"']*duplicator[^"']*["'])`,
	"RankMath SEO": `(?i)(rankmath-|data-rankmath-|class=["'][^"']*rankmath[^"']*["'])`,
	"SEOPress": `(?i)(seopress-|data-seopress-|class=["'][^"']*seopress[^"']*["'])`,
	"WP Recipe Maker": `(?i)(wprm-|data-wprm-|class=["'][^"']*wprm[^"']*["'])`,
	"WP Store Locator": `(?i)(wpsl-|data-wpsl-|class=["'][^"']*wpsl[^"']*["'])`,
	"AffiliateWP": `(?i)(affiliatewp-|data-affiliatewp-|class=["'][^"']*affiliatewp[^"']*["'])`,
	"GiveWP": `(?i)(givewp-|data-givewp-|class=["'][^"']*givewp[^"']*["'])`,
	"MemberPress": `(?i)(memberpress-|data-memberpress-|class=["'][^"']*memberpress[^"']*["'])`,
	"WP User Avatar": `(?i)(wp-user-avatar-|data-wp-user-avatar-|class=["'][^"']*wp-user-avatar[^"']*["'])`,
	"Envira Gallery": `(?i)(envira-|data-envira-|class=["'][^"']*envira[^"']*["'])`,
	"FooGallery": `(?i)(foogallery-|data-foogallery-|class=["'][^"']*foogallery[^"']*["'])`,
	"WP Google Maps": `(?i)(wpgm-|data-wpgm-|class=["'][^"']*wpgm[^"']*["'])`,
	"WP RSS Aggregator": `(?i)(wprss-|data-wprss-|class=["'][^"']*wprss[^"']*["'])`,
	"WP Security Audit Log": `(?i)(wsal-|data-wsal-|class=["'][^"']*wsal[^"']*["'])`,
	"Social Warfare": `(?i)(social-warfare-|data-social-warfare-|class=["'][^"']*social-warfare[^"']*["'])`,
	"MailPoet": `(?i)(mailpoet-|data-mailpoet-|class=["'][^"']*mailpoet[^"']*["'])`,
	"Thrive Architect": `(?i)(thrive-|data-thrive-|class=["'][^"']*thrive[^"']*["'])`,
	"UpdraftPlus": `(?i)(updraftplus-|data-updraftplus-|class=["'][^"']*updraftplus[^"']*["'])`,
	"WP Smush": `(?i)(wp-smush-|data-wp-smush-|class=["'][^"']*wp-smush[^"']*["'])`,
	"NitroPack": `(?i)(nitropack-|data-nitropack-|class=["'][^"']*nitropack[^"']*["'])`,
	"W3 Total Cache": `(?i)(w3-total-cache-|data-w3-total-cache-|class=["'][^"']*w3-total-cache[^"']*["'])`,
	"Loco Translate": `(?i)(loco-translate-|data-loco-translate-|class=["'][^"']*loco-translate[^"']*["'])`,
}


var WPFirewallPatterns = map[string]string{
    "Cloudflare": `(?i)(cdn-cgi|cloudflare-|data-cloudflare-|class=["'][^"']*cloudflare[^"']*["'])`,
    "Wordfence": `(?i)(wordfence-|wf-|data-wordfence-|class=["'][^"']*wordfence[^"']*["'])`,
    "Sucuri": `(?i)(sucuri-|data-sucuri-|class=["'][^"']*sucuri[^"']*["'])`,
    "MalCare": `(?i)(malcare-|data-malcare-|class=["'][^"']*malcare[^"']*["'])`,
    "Shield Security": `(?i)(shield-security-|data-shield-security-|class=["'][^"']*shield-security[^"']*["'])`,
    "BulletProof Security": `(?i)(bulletproof-security-|data-bulletproof-security-|class=["'][^"']*bulletproof-security[^"']*["'])`,
    "Cerber Security": `(?i)(cerber-security-|data-cerber-security-|class=["'][^"']*cerber-security[^"']*["'])`,
    "Ninja Firewall": `(?i)(ninja-firewall-|data-ninja-firewall-|class=["'][^"']*ninja-firewall[^"']*["'])`,
    "SecuPress": `(?i)(secupress-|data-secupress-|class=["'][^"']*secupress[^"']*["'])`,
    "iThemes Security": `(?i)(ithemes-security-|data-ithemes-security-|class=["'][^"']*ithemes-security[^"']*["'])`,
    "WP Security Audit Log": `(?i)(wsal-|data-wsal-|class=["'][^"']*wsal[^"']*["'])`,
    "SiteLock": `(?i)(sitelock-|data-sitelock-|class=["'][^"']*sitelock[^"']*["'])`,
    "WP Hide & Security Enhancer": `(?i)(wp-hide-|data-wp-hide-|class=["'][^"']*wp-hide[^"']*["'])`,
    "Security Ninja": `(?i)(security-ninja-|data-security-ninja-|class=["'][^"']*security-ninja[^"']*["'])`,
    "All In One WP Security": `(?i)(aio-wp-security-|data-aio-wp-security-|class=["'][^"']*aio-wp-security[^"']*["'])`,
    "Block Bad Queries (BBQ)": `(?i)(bbq-|data-bbq-|class=["'][^"']*bbq[^"']*["'])`,
    "WP Fail2Ban": `(?i)(fail2ban-|data-fail2ban-|class=["'][^"']*fail2ban[^"']*["'])`,
    "Login Lockdown": `(?i)(login-lockdown-|data-login-lockdown-|class=["'][^"']*login-lockdown[^"']*["'])`,
    "Limit Login Attempts Reloaded": `(?i)(limit-login-attempts-|data-limit-login-attempts-|class=["'][^"']*limit-login-attempts[^"']*["'])`,
    "Hide My WP": `(?i)(hide-my-wp-|data-hide-my-wp-|class=["'][^"']*hide-my-wp[^"']*["'])`,
    "WP Hide Login": `(?i)(wp-hide-login-|data-wp-hide-login-|class=["'][^"']*wp-hide-login[^"']*["'])`,
    "Defender Security": `(?i)(defender-security-|data-defender-security-|class=["'][^"']*defender-security[^"']*["'])`,
    "WebARX": `(?i)(webarx-|data-webarx-|class=["'][^"']*webarx[^"']*["'])`,
    "FastGuard": `(?i)(fastguard-|data-fastguard-|class=["'][^"']*fastguard[^"']*["'])`,
    "VaultPress": `(?i)(vaultpress-|data-vaultpress-|class=["'][^"']*vaultpress[^"']*["'])`,
    "FireWall IP": `(?i)(firewall-ip-|data-firewall-ip-|class=["'][^"']*firewall-ip[^"']*["'])`,
    "Anti-Malware Security": `(?i)(anti-malware-security-|data-anti-malware-security-|class=["'][^"']*anti-malware-security[^"']*["'])`,
    "WP Malware Scanner": `(?i)(wp-malware-scanner-|data-wp-malware-scanner-|class=["'][^"']*wp-malware-scanner[^"']*["'])`,
    "Patchstack": `(?i)(patchstack-|data-patchstack-|class=["'][^"']*patchstack[^"']*["'])`,
    "Jetpack Security": `(?i)(jetpack-security-|data-jetpack-security-|class=["'][^"']*jetpack-security[^"']*["'])`,
    "BitNinja": `(?i)(bitninja-|data-bitninja-|class=["'][^"']*bitninja[^"']*["'])`,
    "ModSecurity": `(?i)(modsecurity-|data-modsecurity-|class=["'][^"']*modsecurity[^"']*["'])`,
    "WordPress Sentinel": `(?i)(wordpress-sentinel-|data-wordpress-sentinel-|class=["'][^"']*wordpress-sentinel[^"']*["'])`,
    "Smart Security Tools": `(?i)(smart-security-tools-|data-smart-security-tools-|class=["'][^"']*smart-security-tools[^"']*["'])`,
    "WP Security Scanner": `(?i)(wp-security-scanner-|data-wp-security-scanner-|class=["'][^"']*wp-security-scanner[^"']*["'])`,
    "Fortress Security": `(?i)(fortress-security-|data-fortress-security-|class=["'][^"']*fortress-security[^"']*["'])`,
    "Reblaze": `(?i)(reblaze-|data-reblaze-|class=["'][^"']*reblaze[^"']*["'])`,
    "Imunify360": `(?i)(imunify360-|data-imunify360-|class=["'][^"']*imunify360[^"']*["'])`,
    "CyberPanel Firewall": `(?i)(cyberpanel-firewall-|data-cyberpanel-firewall-|class=["'][^"']*cyberpanel-firewall[^"']*["'])`,
    "SiteGround Security": `(?i)(siteground-security-|data-siteground-security-|class=["'][^"']*siteground-security[^"']*["'])`,
    "StackPath WAF": `(?i)(stackpath-waf-|data-stackpath-waf-|class=["'][^"']*stackpath-waf[^"']*["'])`,
    "Cloudbric": `(?i)(cloudbric-|data-cloudbric-|class=["'][^"']*cloudbric[^"']*["'])`,
    "AWS Shield": `(?i)(aws-shield-|data-aws-shield-|class=["'][^"']*aws-shield[^"']*["'])`,
    "Imperva WAF": `(?i)(imperva-waf-|data-imperva-waf-|class=["'][^"']*imperva-waf[^"']*["'])`,
}


var CMSPatterns = map[string]string{
	"WordPress":          `(?i)(wp-(content|includes)|<meta name=["']generator["'] content=["']WordPress[^"']*["'])`,
	"Joomla":             `(?i)(\/media\/system\/js|<meta name=["']generator["'] content=["']Joomla[^"']*["'])`,
	"Drupal":             `(?i)(\/sites\/(default|all)\/|<meta name=["']Generator["'] content=["']Drupal[^"']*["'])`,
	"Concrete CMS":       `(?i)(concrete5|concrete\.js|concrete5\/themes)`,
	"SilverStripe":       `(?i)(silverstripe|framework\/core)`,
	"TYPO3":              `(?i)(typo3\/|t3lib\/|<meta name=["']generator["'] content=["']TYPO3[^"']*["'])`,
	"Plone":              `(?i)(Plone\/|<meta name=["']generator["'] content=["']Plone[^"']*["'])`,
	"Umbraco":            `(?i)(Umbraco\/|<meta name=["']generator["'] content=["']Umbraco[^"']*["'])`,
	"Neos CMS":           `(?i)(Neos\.|NeosCMS|fusion\/objects|typo3fluid)`,
	"Bolt CMS":           `(?i)(bolt\/theme|bolt\.js|Powered by Bolt)`,
	"Textpattern":        `(?i)(textpattern|<meta name=["']generator["'] content=["']Textpattern[^"']*["'])`,
	"SPIP":               `(?i)(ecrire\/|spip\.php|<meta name=["']generator["'] content=["']SPIP[^"']*["'])`,
	"Fork CMS":           `(?i)(fork-cms|<meta name=["']generator["'] content=["']Fork CMS[^"']*["'])`,
	"Redaxo":             `(?i)(redaxo|rex_article|<meta name=["']generator["'] content=["']REDAXO[^"']*["'])`,
	"WonderCMS":          `(?i)(wondercms|<meta name=["']generator["'] content=["']WonderCMS[^"']*["'])`,
	"Publify":            `(?i)(Publify|typo\/stylesheets)`,
	"Omeka":              `(?i)(omeka-(classic|s)|<meta name=["']generator["'] content=["']Omeka[^"']*["'])`,
	"Exponent CMS":       `(?i)(exponentcms|exponent_bootstrap)`,
	"Lektor":             `(?i)(lektor|Powered by Lektor)`,
	"Pelican":            `(?i)(pelican\.css|pelican\.js|Powered by Pelican)`,
	"Mezzanine":          `(?i)(mezzanine|mezzanine\.js)`,
	"Kotti":              `(?i)(kotti|kotti\.static)`,
	"FeinCMS":            `(?i)(feincms|Powered by FeinCMS)`,
	"Quokka CMS":         `(?i)(quokka|Powered by Quokka)`,
	"Wagtail":            `(?i)(wagtail|wagtailadmin|Powered by Wagtail)`,
	"Superdesk":          `(?i)(superdesk|contentapi|superdesk\.js)`,
	"Strapi":             `(?i)(strapi\/admin|<title>Strapi Admin|strapi\.io)`,
	"Payload CMS":        `(?i)(payloadcms|\/admin\/payload)`,
	"Squidex":            `(?i)(squidex|\/api\/content\/)`,
	"Roadiz":             `(?i)(roadiz|rz-admin)`,
	"WinterCMS":          `(?i)(wintercms|winter\.js|cms\/themes)`,
	"Rapido":             `(?i)(rapido-cms|Powered by Rapido)`,
	"Typemill":           `(?i)(typemill|typemill\.js|\/tm\/assets)`,
	"Sveltia CMS":        `(?i)(sveltia|Powered by Sveltia)`,
	"Manifest CMS":       `(?i)(manifestcms|manifest\.yml)`,
	"OpenCms":            `(?i)(opencms\/|Powered by OpenCms)`,
	"Tiki Wiki CMS":      `(?i)(tikiwiki|tiki-(index|page|login))`,
	"ImpressPages":       `(?i)(impresspages|ipContent)`,
	"ProcessWire":        `(?i)(processwire|\/site\/assets\/|\/wire\/)`,
	"MODX":               `(?i)(modx|assets\/components|<meta name=["']generator["'] content=["']MODX[^"']*["'])`,
	"ExpressionEngine":   `(?i)(expressionengine|EE\.|\/system\/ee)`,
	"Kentico CMS":        `(?i)(kentico|CMSModules|CMSPages)`,
	"Django CMS":         `(?i)(django\.cms|{% load cms_tags %}|django\.js)`,
	"Grav":               `(?i)(grav|user\/pages|\/system\/assets)`,
	"CMSimple":           `(?i)(cmsimple|cmsimple\.css)`,
	"eZ Publish":         `(?i)(ezpublish|ezjscore|eZ\.js)`,
	"UMI.CMS":            `(?i)(umi\.cms|UMI\.js|Powered by UMI)`,
	"Statamic":           `(?i)(statamic|\/cp\/|\/site\/content)`,
	"Koken":              `(?i)(koken|koken\.js|\/storage\/themes)`,
	"Movable Type":       `(?i)(movabletype|mt\.js|mt-static)`,
	"Simplébo":           `(?i)(simplebo|Powered by Simplébo)`,
	"XpressEngine":       `(?i)(xpressengine|xe\.js|modules\/admin)`,
	"Dynamicweb":         `(?i)(dynamicweb|dwcontent|dwapi)`,
	"DataLife Engine":    `(?i)(datalifeengine|engine\/classes)`,
	"DNN":                `(?i)(dnn|dotnetnuke|\/DesktopModules\/)`,
	"Webflow":            `(?i)(webflow|webflow\.js|Powered by Webflow)`,
	"HubSpot CMS Hub":    `(?i)(hs-script-loader|hs-analytics|Powered by HubSpot)`,
	"Cargo":              `(?i)(cargo\.site|cargo\.js|Powered by Cargo)`,
	"Strato Website":     `(?i)(strato-editor|Powered by Strato)`,
	"Sitecore":           `(?i)(sitecore|sc_default\.js)`,
	"WebNode":            `(?i)(webnode|Powered by Webnode)`,
	"Contao":             `(?i)(contao|TL_FILES|<meta name=["']generator["'] content=["']Contao[^"']*["'])`,
	"Tilda":              `(?i)(tilda\.css|tilda-block|Powered by Tilda)`,
	"Duda":               `(?i)(duda|dudaone|cdn\.duda\.co)`,
}
